### ISSUE TITLE
Invalid values received if bms also connected to PC

### ISSUE THREAD

**Issue by MishuPtm** [syssi/esphome-seplos-bms#102]
I am using this with Seplos 10E V2 bms, via RS485, however, if I connect the BMS to BatteryMonitor via the other RS485 port, the values fluctuate out of range:
![image](https://github.com/syssi/esphome-seplos-bms/assets/28862976/287c666e-5ecd-45aa-aeb0-0ca6d9eafc09)

**Comment by syssi** [comment]
Could you try to provide some logs too? Do you see CRC errors here or does the BMS really push faulty measurements?

**Comment by syssi** [comment]
Closed because of inactivity.
