### ISSUE TITLE
max  battery bank's  ? 

### ISSUE THREAD

**Issue by andyprv** [syssi/esphome-seplos-bms#69]
in theory there can be  15 BMS Moduls on the RS485 Bus .
But it seams after  >5 battery bank entry's  i get some memory problems.

Iam not sure where the code  crashes .  look like during mqtt  or debug preparing.

**Comment by syssi** [comment]
You could try to add a single sensor (f.e. total voltage) per BMS. Does the ESP survive in this case? The ESP cashs if you hit the resource limits.
