### ISSUE TITLE
1101-JK06 no data being received

### ISSUE THREAD

**Issue by Pho3niX90** [syssi/esphome-seplos-bms#74]
So just recently purchased the ESP32 and a TTL converted, I set  everything up, and ran in debug mode. RJ45 is connected to the first RS485  next to the CAN.

On the converter, I can see the periodic tx, but RX is never triggered.

- I have used the `esp32-example.yaml` and have tried both 19200 and 9600 without success. 
- I have tested the continuity of the RJ45, and all checks out. 
- I have tried using the second RJ45 port, no success. 

Here is the debug info:
![image](https://github.com/syssi/esphome-seplos-bms/assets/7858187/43f03feb-7f68-49e8-affa-d9c1e9ba7d42)

The converter being used:
![image](https://github.com/syssi/esphome-seplos-bms/assets/7858187/fb1ef393-c26b-48bd-9d17-07ba284e33d9)

I do see the following warning about GPIO5, not sure if it's related:
![image](https://github.com/syssi/esphome-seplos-bms/assets/7858187/2e2dcdf2-e5e1-45cc-8594-ab07e0d78573)

**Comment by Pho3niX90** [comment]
So this can be ignored. Tried the following:
` tx_pin: GPIO5
  rx_pin: GPIO4`

Shortly after I noticed the following picture:
![image](https://github.com/syssi/esphome-seplos-bms/assets/7858187/8cf004ee-d92e-440d-8736-e9d72ec75671)


This would then be a confirmation that this specific seplos E10 v2 (rebranded as Apexium Apex) works with the software, baud rate `19200`

**Comment by syssi** [comment]
Could you provide some more details about your BMS model? So you are able to talk to your BMS using this component now?

**Comment by Pho3niX90** [comment]
So the BMS in question is branded as a "Apex 48200", it's supplied by Docan/Apexium 
[Apex BMS 48V200A-compressed.pdf](https://github.com/syssi/esphome-seplos-bms/files/13464207/Apex.BMS.48V200A-compressed.pdf)

It is actually a Seplos E10 (v2), 
![image](https://github.com/syssi/esphome-seplos-bms/assets/7858187/393959c0-2a93-4f2d-a34e-c8755965e7ab)
Manufacturer Info: CAN:PNG_DYE_Luxp_TBB
Part Model: 1101-JK06
Software Version: 16.7
Protocol Version: 2.0

**Comment by syssi** [comment]
Perfect! I will add the model to the list of supported devices and will close this issue.

**Comment by syssi** [comment]
See 4688c849fd9d0a0ae17c6ccc8b0d6b6777516ea6

**Comment by SieueNhaan** [comment]
I want to connect the address with esp so what is the seplos master address ,What address is needed to connect to seplos master, dip 5 on (pack mateter), dip 1 on pack 1

**Comment by Pho3niX90** [comment]
> I want to connect the address with esp so what is the seplos master address ,What address is needed to connect to seplos master, dip 5 on (pack mateter), dip 1 on pack 1

address I used was `0x00`, but I have a single pack. You can try `0x10` if dip switch 5 is the only one on
