### ISSUE TITLE
esp32-seplos-v3-example.yaml wrong board configured

### ISSUE THREAD

**Issue by mager33** [syssi/esphome-seplos-bms#88]
Would that be right?

```
esp32:
  board: esp32dev
  framework:
    type: arduino
```

**Comment by syssi** [comment]
Why do you prefer the Arduino framework over esp-idf?

**Comment by mager33** [comment]
That was auto-generated bei ESPhome; I am not into technical details. Just wanted to mention that the example code will not work as it is now. Easy fix, though!

**Comment by syssi** [comment]
I don't want to change the default framework back to `Arduino`. If no Raspberry Pi is used the `ESP-IDF` framework should work out of the box.
